name: Release and Publish # Re-trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        working-directory: ./packages/mcp-server

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config pull.rebase false

      - name: Build project
        run: bun run build
        working-directory: ./packages/mcp-server

      - name: Debug - Check git history before release
        working-directory: ./packages/mcp-server
        run: |
          echo "=== GIT CONFIGURATION ==="
          git config -l | grep -E "user.name|user.email"
          echo ""
          echo "=== CURRENT BRANCH ==="
          git branch -a
          echo ""
          echo "=== RECENT COMMITS ==="
          git log --oneline --decorate -15
          echo ""
          echo "=== TAGS ==="
          git tag -l
          echo ""
          echo "=== PACKAGE VERSION ==="
          cat package.json | grep version
          echo ""
          echo "=== SEMANTIC RELEASE DRY RUN ==="
          npx semantic-release --dry-run

      - name: Run semantic-release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        working-directory: ./packages/mcp-server

      - name: Create Distribution Package
        if: steps.semantic-release.outputs.new_release_published == 'true'
        run: |
          # Create distribution directory
          mkdir -p dist-package
          
          # Copy essential files
          cp package.json dist-package/
          cp README.md dist-package/ 2>/dev/null || true
          cp LICENSE dist-package/ 2>/dev/null || true
          
          # Copy built distribution files
          find . -name "dist" -type d -exec cp -r {} dist-package/ \;
          
          # Update package.json version if new release
          VERSION="${{ steps.semantic-release.outputs.new_release_version }}"
          if [ ! -z "$VERSION" ]; then
            cd dist-package
            npm version "$VERSION" --no-git-tag-version
            cd ..
          fi

      - name: Create Release Archive
        if: steps.semantic-release.outputs.new_release_published == 'true'
        run: |
          cd dist-package
          tar -czf ../unity-mcp-${{ steps.semantic-release.outputs.new_release_version }}.tar.gz *
          cd .. 